# Generated by Django 6.0 on 2026-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_external_id'),
        ('sources', '0003_alter_source_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='external_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('external_id', 'source_id')},
        ),
    ]
