# Generated by Django 6.0 on 2026-01-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.JSONField(),
        ),
    ]
