# Generated by Django 6.0 on 2026-01-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='current_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user_attributes',
            field=models.JSONField(default=dict),
        ),
    ]
