# Generated by Django 6.0 on 2026-02-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_remove_message_current_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
