# Generated by Django 6.0 on 2026-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_message_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
