# Generated by Django 6.0 on 2026-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0006_message_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='message',
            name='external_comment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
