# Generated by Django 6.0 on 2026-02-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0007_remove_message_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
