# Generated by Django 6.0 on 2026-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0008_conversation_last_followup_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_followup',
            field=models.BooleanField(default=False),
        ),
    ]
