# Generated by Django 6.0 on 2026-01-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
