# Generated by Django 6.0 on 2026-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_source_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], max_length=50, unique=True),
        ),
    ]
