# Generated by Django 6.0 on 2026-01-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_source_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('dm', 'Direct Message'), ('post_comment', 'Post Comment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('threads', 'Threads')], max_length=50, unique=True),
        ),
    ]
