# Generated by Django 6.0 on 2026-02-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_source_source_type_alter_source_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='app_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('threads', 'Threads')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('platform', 'source_type')},
        ),
    ]
