# Generated by Django 6.0 on 2026-02-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_alter_source_app_id_alter_source_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='app_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
