# Generated by Django 6.0 on 2026-02-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_leadscoringrule_delete_leadscroingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
