# Generated by Django 6.0 on 2026-02-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='meeting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='meeting_time',
            field=models.TimeField(),
        ),
    ]
