# Generated by Django 6.0 on 2026-02-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_meeting_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_id',
        ),
    ]
