# Generated by Django 6.0 on 2026-02-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='lead_id',
            new_name='client_id',
        ),
    ]
