# Generated by Django 6.0 on 2026-02-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_lead_id_booking_client_id'),
        ('clients', '0003_alter_client_external_id_and_more'),
        ('lead', '0003_lead_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lead_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lead.lead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
